name: Run Unit Tests

on:
  push:
    branches:
      - main
      - '**' # Runs on all branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Specify the Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests with coverage
    - name: Run tests
      run: |
        pytest -v --cov=src/problem_solving_questions --cov-report=html --cov-report=term tests/